auth_system/urls.py
from django.urls import path
from auth_system import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignUpView.as_view(), name="signup"),
]

app_name = "auth_system"

tasks/urls.py
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name="task-list"),
    path('<int:pk>/', views.TaskDetailView.as_view(), name="task-detail"),
    path('task-create', views.TaskCreateView.as_view(), name="task-create"),
    path('update/<int:pk>/', views.TaskUpdateView.as_view(), name="task-update"),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name="task-delete"),
    path('comment/like/<int:pk>', views.CommentLikeToggle.as_view(), name="comment-like-toggle"),
    path('comment/update/<int:pk>', views.CommentUpdateView.as_view(), name="comment-update"),
    path('comment/delete/<int:pk>', views.CommentUpdateView.as_view(), name="comment-delete"),
]

app_name = "tasks"

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('', include('auth_system.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Система управління завданнями</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        {% load static %}
        <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
          <div class="col-md-3 mb-2 mb-md-0">
            <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
              <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>
          </div>
    
          <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'tasks:task-list' %}" class="dark-nav-link px-2">Home</a></li>
            <li><a href="" class="light-nav-link px-2">Active</a></li>
          </ul>
    
          <div class="col-md-3 text-end">
            <a href="{% url 'auth_system:login' %}"class="light-grey-outline-btn me-2">Login</a>
            <a href="{% url 'auth_system:signup' %}" class="light-grey-btn">Sign-up</a>
            <form action="{% url 'auth_system:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="grey-btn me-2" style="vertical-align: middle;">Logout</button>
            </form>
          </div>
        </header>
      </div>
    
    {% block content %}
    {% endblock content%}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>