tasks/urls.py
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.TaskListView.as_view(), name="task-list"),
    path('<int:pk>/', views.TaskDetailView.as_view(), name="task-detail"),
    path('task-create', views.TaskCreateView.as_view(), name="task-create"),
    path('update/<int:pk>/', views.TaskUpdateView.as_view(), name="task-update"),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name="task-delete"),
    path('comment/like/<int:pk>', views.CommentLikeToggle.as_view(), name="comment-like-toggle"),
    path('comment/update/<int:pk>', views.CommentUpdateView.as_view(), name="comment-update"),
    path('comment/delete/<int:pk>', views.CommentUpdateView.as_view(), name="comment-delete"),
]

app_name = "tasks"

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('', include('auth_system.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Task(models.Model):
    
    STATUS_CHOICES = [
        ["to_do", "To Do"],
        ["in_progress", "In Progress"],
        ["done", "Done"],
    ]
    
    PRIORITY_CHOICES = [
        ["low", "Low"],
        ["medium", "Medium"],
        ["high", "High"],
        ["cricital", "Cricital"]
    ]
    
    title = models.CharField(max_length=63)
    description = models.TextField()
    status = models.CharField(max_length=31, choices=STATUS_CHOICES, default="to_do")
    priority = models.CharField(max_length=31, choices=PRIORITY_CHOICES, default="medium")
    due_date = models.DateTimeField(null=True, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tasks")
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tasks:task-detail', kwargs={'pk': self.pk})
    

class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    media = models.FileField(upload_to="comments_media/", blank=True, null=True)

    def __str__(self):
        return self.task.title
    
    def get_absolute_url(self):
        return self.task.get_absolute_url()
    

class Like(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_comments')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('comment', 'user') 

tasks/forms.py
from django import forms
from tasks.models import Task, Comment
from django.forms import TextInput, FileInput, DateTimeInput, Textarea, RadioSelect

STATUS_CHOICES = [
        ["to_do", "To Do"],
        ["in_progress", "In Progress"],
        ["done", "Done"],
    ]
    
PRIORITY_CHOICES = [
            ["low", "Low"],
            ["medium", "Medium"],
            ["high", "High"],
            ["cricital", "Cricital"]
        ]

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "status", "priority", "due_date"]
    
    title = forms.CharField(
            label='Title',
            widget=forms.TextInput(
                attrs = {
                    'class': "form-control rounded-3",
                    'id': "title",
                    'placeholder': 'Title',
                    'style': 'max-width: 300px;'
                }
            )
        )
        
    description = forms.CharField(
        widget=forms.Textarea(
            attrs = {
                'class': "form-control rounded-3",
                'id': "description",
                'placeholder': 'Description',
                'style': 'max-width: 300px;'
            }
        )
    )
    
    status = forms.CharField(
        label='Status',
        widget=forms.Select(
            attrs = {
                'class': "form-control rounded-3",
                'id': "status",
                'placeholder': 'Status',
                'style': 'max-width: 300px;'
            },
            choices=STATUS_CHOICES
        )
    )
    
    priority = forms.CharField(
        label='Priority',
        widget=forms.Select(
            attrs = {
                'class': "form-control rounded-3",
                'id': "priority",
                'placeholder': 'Priority',
                'style': 'max-width: 300px;'
            },
            choices=PRIORITY_CHOICES
        )
    )
    
    due_date = forms.DateTimeField(
        label='Due Date',
        widget=forms.DateTimeInput(
            attrs = {
                'class': "form-control rounded-3",
                'id': "due_date",
                'placeholder': 'Due Date',
                'style': 'max-width: 300px;',
                'type': 'datetime-local'
            }
        )
    )
        
class TaskFilterForm(forms.Form):
            
    STATUS_CHOICES = [
        ["", "All"],
        ["user_owner", "My tasks"]
    ]
    
    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False)
    
    def __init__(self, *args, **kwargs):
        super(TaskFilterForm, self).__init__(*args, **kwargs)
        self.fields["status"].widget.attrs.update({"class": "form-control"})
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ['content', 'media']
        
    content = forms.CharField(
        label='Content',
        widget=forms.Textarea(
            attrs = {
                'class': "form-control rounded-3",
                'id': "content",
                'placeholder': 'Content',
                'style': 'max-width: 300px;'
            },
        )
    )
    
    media = forms.FileField(
        label = 'Media',
        widget = forms.FileInput(
            attrs={
                'msg cols': '30',
                'rows': '5',
                'class': 'form-control',
                'style': 'border: 1px solid #4c486b;',
                'label': 'Media'
            },
        )
    )

tasks/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.urls import reverse_lazy
from tasks.models import Task, Comment, Like
from tasks.forms import TaskForm, TaskFilterForm, CommentForm
from tasks.mixins import UserIsOwnerMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.core.exceptions import PermissionDenied

class TaskListView(ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "tasks/task_list.html"
    def get_queryset(self):
        queryset = super().get_queryset()
        status = self.request.GET.get('status', '')
        if status:
            queryset = queryset.filter(status=status)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = TaskFilterForm(self.request.GET)
        return context
    
    
class TaskDetailView(DetailView):
    model = Task
    context_object_name = "task"
    template_name = "tasks/task_detail.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context
    
    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST, request.FILES)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.task = self.get_object()
            comment.save()
            return redirect('tasks:task-detail', pk = comment.task.pk)
            

class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/task_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")
    
    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)
    
    
class TaskUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Task
    template_name = "tasks/task_edit_form.html"
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")
    
    
class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/task_confirm_delete.html"
    success_url = reverse_lazy("tasks:task-list")
    
class CommentLikeToggle(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
        like_qs = Like.objects.filter(comment=comment, user=request.user)
        if like_qs.exists():
            like_qs.delete()
        else:
            Like.objects.create(comment=comment, user=request.user)
        return HttpResponseRedirect(comment.get_absolute_url())
    
class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ['content', 'media']
    template_name = 'tasks/task_edit_comment.html'

    def form_valid(self, form):
        comment = self.get_object()
        if comment.author != self.request.user:
            raise PermissionDenied("Ви не можете редагувати цей коментар.")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('tasks:task_detail', kwargs={'pk': self.object.task.pk})


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'tasks/task_comment_confirm_delete.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author=self.request.user)

    def get_success_url(self):
        return reverse_lazy('tasks:task_detail', kwargs={'pk': self.object.task.pk})

templates/tasks/task_comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Comment delete</h2>
    <p>Are you sure you want to delete this comment?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="grey-btn">Yes, delete</button>
        <a href="{{ request.META.HTTP_REFERER }}" style="color: #BDBFB7;">Відміна</a>
    </form>
</div>
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Task delete</h2>
    <p>Are you sure you want to delete "{{ object.title }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="grey-btn">Yes, delete</button>
        <a href="{% url 'tasks:task-list' %}" style="color: #BDBFB7;">No, go back to task list</a>
    </form>
</div>
{% endblock %}

templates/tasks/task_detail.html
{% extends 'base.html' %}
{% block content %}
{% load custom_tags %}
  <div class="container-sm">
    <section class="card-task-detail">
      <header>
        <p>{{ task.title }}</p>
        <p style="font-size: 10px; color: #BDBFB7;">{{ task.due_date }}</p>
      </header>
      <main>
        <p>{{ task.description }}</p>
      </main>
      <footer>
        {% if task.priority == "low" %}
        <span class="badge text-bg-secondary">{{ task.priority }}</span>
        {% elif task.priority == "medium" %}
        <span class="badge text-bg-primary">{{ task.priority }}</span>
        {% elif task.priority == "high" %}
        <span class="badge text-bg-warning">{{ task.priority }}</span>
        {% else %}
        <span class="badge text-bg-danger">{{ task.priority }}</span>
        {% endif %}
        {% if task.status == "to_do" %}
        <span class="badge text-bg-warning">{{ task.status }}</span>
        {% elif task.status == "in_progress" %}
        <span class="badge text-bg-secondary">{{ task.status }}</span>
        {% elif task.status == "done" %}  
        <span class="badge text-bg-success">{{ task.status }}</span>
        {% else %}
        <span class="badge text-bg-dark">{{ task.status }}</span>
        {% endif %}
        <a href="{% url 'tasks:task-update' task.id %}" id="post" class="grey-btn">Edit</a>
        <a href="{% url 'tasks:task-delete' task.id %}" id="post" class="grey-btn">Delete</a>
      </footer>
    </section>  

    <!-- Коментарі -->
    <section>
      <div class="row">
        <div class="col-sm-5 col-md-6 col-12 pb-4">
          <h1>Comments</h1>
            {% for comment in task.comments.all %}
              <div class="text-justify lighter mt-4 float-right">
                <h4>{{ comment.author.username }}</h4>
                <h6 class="card-subtitle mb-2">{{ comment.created_at }}</h6>
                <p>{{ comment.content }}</p>
                {% if comment.media %}
                  <div style="padding-bottom: 5px;">
                    <div class="comment-media">
                        {% if comment.media.url|endswith:".jpg" or comment.media.url|endswith:".png" or comment.media.url|endswith:".jpeg" %}
                            <img src="{{ comment.media.url }}" alt="Зображення коментаря" style="max-width: 300px;">
                        {% elif comment.media.url|endswith:".mp4" %}
                            <video width="320" height="240" controls>
                                <source src="{{ comment.media.url }}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                        {% else %}
                            <a href="{{ comment.media.url }}">Download file</a>
                        {% endif %}
                      </div>
                    </div>
                {% endif %}
                <form action="{% url 'tasks:comment-like-toggle' comment.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="light-greyy-btn">
                    ❤️{{ comment.likes.count }}
                  </button>
                </form>
                <footer>
                  <a href="{% url 'tasks:comment-update' comment.id %}" id="post" class="grey-btn">Edit</a>
                  <a href="{% url 'tasks:comment-delete' comment.id %}" id="post" class="grey-btn">Delete</a>
                </footer>
                </div>
            {% empty %}
                <p>No comments</p>
            {% endfor %}
              </div>

        <!-- Форма додавання коментаря -->
        <div class="col-lg-4 col-md-5 col-sm-4 offset-md-1 offset-sm-1 col-12 mt-4">
            <form action="{% url 'tasks:task-detail' task.id %}" method="post" enctype="multipart/form-data" class="formm">
              <div class="formm-group">
                {% csrf_token %}
                <h4>Leave a comment</h4>
                {{ comment_form.content }}
                <br>
                {{ comment_form.media }}
                <br>
                <button type="submit" id="post" class="grey-btn">Post Comment</button> 
              </div>
              </form>
        </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/tasks/task_edit_comment.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div class="container grey-background">
            <br>
            <h1 style="color: #fff;">Edit comment</h1>
            <form method="post">
                {% csrf_token %}
                <div class="formm-group">
                    {{ form.content }}
                    <br>
                    {{ form.media.url }}
                </div>
                <br>
                <button type="submit" class="grey-btn">Edit comment</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/tasks/task_edit_form.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div class="container grey-background">
            <br>
            <h1 style="color: #fff;">Edit Task</h1>
            <form action="{% url 'tasks:task-list' %}" method="post">
                {% csrf_token %}
                <div class="formm-group">
                    {{ form.title }}
                    <br>
                    {{ form.description }}
                    <br>
                    {{ form.status }}
                    <br>
                    {{ form.priority }}
                    <br>
                    {{ form.due_date }}
                </div>
                <br>
                <input type="submit" class="grey-btn" value="Edit Task">
            </div>
            </form>
        </div>
{% endblock content %}

templates/tasks/task_form.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div class="container">
            <h1>Додати завдання</h1>
            <form action="{% url 'tasks:task-list' %}" method="post">
                {% csrf_token %}
            <div class="container-sm">
                <div class="form-group">
                    {{ form.title }}
                </div>
                <br>
                <div class="form-group">
                    {{ form.description }}
                </div>
                <br>
                <div class="form-group">
                    {{ form.status }}
                </div>
                <br>
                <div class="form-group">
                    {{ form.priority }}
                </div>
                <br>
                <div class="form-group">
                    {{ form.due_date }}
                </div>
                <br>
                <div class="form-group">
                    <input class="btn btn-primary" type="submit" value="Відправити">
                </div>
            </div>
            </form>
        </div>
{% endblock content %}

templates/tasks/task_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <h2>Task list</h2>
    </div>
            <div class="task-row">
                <div class="task-column-left">
                  <h4 style="font-size: 600; color: #fff;">To do</h4>
                  {% for task in tasks %}
                  {% if task.status == "to_do" %}
                  <section class="card-task">
                    <header>
                      <p>{{ task.title }}</p>
                      <a href="{% url 'tasks:task-detail' task.pk %}">Details</a>
                    </header>
                  </section>
                  {% endif %}
                  {% endfor %}
                  <a href="{% url 'tasks:task-create' %}" class="grey-btn">Add Task</a>
                </div>
                <div class="task-column-middle">
                  <h4 style="font-size: 600; color: #fff;">In Progress</h4>
                  {% for task in tasks %}
                  {% if task.status == "in_progress" %}
                  <section class="card-task">
                    <header>
                      <p>{{ task.title }}</p>
                      <a href="{% url 'tasks:task-detail' task.pk %}">Details</a>
                    </header>
                  </section>
                  {% endif %}
                  {% endfor %}
                  <a href="{% url 'tasks:task-create' %}" class="grey-btn">Add Task</a>
                </div>
                <div class="task-column-right">
                  <h4 style="font-size: 600; color: #fff;">Done</h4>
                  {% for task in tasks %}
                  {% if task.status == "done" %}
                  <section class="card-task">
                    <header>
                      <p>{{ task.title }}</p>
                      <a href="{% url 'tasks:task-detail' task.pk %}">Details</a>
                    </header>
                  </section>
                  {% endif %}
                  {% endfor %}
                  <div class="container">
                    <a href="{% url 'tasks:task-create' %}" class="grey-btn">Add Task</a>
                  </div>
              </div>
        </ul>
{% endblock %}